spring.application.name=clientes-service
server.port=0

# Deshabilitar Config Server (por ahora)
spring.cloud.config.enabled=false

# Conexión a Eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.instance.instance-id=${spring.application.name}:${random.value}
eureka.instance.prefer-ip-address=true

# Base de datos MySQL (XAMPP)
spring.datasource.url=jdbc:mysql://localhost:3306/db_clientes?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Flyway
spring.flyway.enabled=true
spring.flyway.baseline-on-migrate=true
spring.flyway.validate-on-migrate=false

# JPA
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true